### PR TITLE
Draft blog post

### PR DESCRIPTION
**Pull request by jimniels**
Draft blog post.

### CODE REVIEW

**Comment by jimniels** [comment]
@sw-yx feast your eyes upon this draft.

**Comment by swyxio** [comment]
checking it out now!

**Comment by swyxio** [comment]
hey Jim, this is really great! I really like the before/after workflow to show how much smoother it is, and then the dropbox + netlify piece is just ace! I've copied my colleagues on this but probably we dont have much further feedback. What are you thinking for title?

**Comment by verythorough** [comment]
This post is awesome! I have a question about the final webhook/function. Does Dropbox send the verification request every time there's a new notification? Or only once at the very beginning? (I couldn't quite be sure after reading their docs.)

If the latter, you could save some function usage by putting it behind a [proxy redirect](https://www.netlify.com/docs/redirects/), like `https://netlibox.netlify.com/my-dropbox-proxy`. For the first verification call, point that redirect to your function, and then after it's verified, change your redirects settings and point it directly to the webhook.

**Comment by jimniels** [comment]
@verythorough 

> Does Dropbox send the verification request every time there's a new notification? Or only once at the very beginning?

It's only once at the very beginning.

>  you could save some function usage by putting it behind a proxy redirect

Very interesting! This seems ideal, as I was thinking "it's a shame I have this Function code which is only needed once, otherwise it's just intercepting the webhook and forwarding it on again".

Allow me to write this out to ensure I understand correctly (and can therefore incorporate these instructions back into the blog post). So the process would be:

1. Have a redirect in `_netlify.toml` like this:
```
[[redirects]]
  from = "/dropbox-webhook"
  to = "/.netlify/functions/dropbox-webhook"
  status = 200
```
2. Deploy site
3. Go to Dropbox and add a webhook URL that points to my proxy URL (i.e. `https://netlibox.netlify.com/dropbox-webhook`). Dropbox will make a verification request, which will get proxied to my custom function, which will send back to the Dropbox API the payload it expects. 
4. Go back into the code and replace the redirect in `_netlify.toml` to now point to the webhook URI that Netlify generates for me, i.e.:
```
[[redirects]]
  from = "/dropbox-webhook"
  to = "https://api.netlify.com/build_hooks/a1b2c34e5f6d7f8g9h"
  status = 200
```

That sound about right? I'm going to give it a try with this repo and make sure I can get it working. Then I'll update the blog post to reflect this process (and the setup instructions in the repo). 

---

@sw-yx 

Good question on title, how about:

- “We hooked up Netlify and Dropbox, you won't believe what happened next...”

Ok, but joking aside, I didn't have any ideas and am totally open to suggestions here. With that said, I'm going to write out a few ideas here and see if anything comes out right:

1. Combining Netlify with Dropbox For a One-Click Publishing Process
2. Netlify + Dropbox: Simplifying the Process of Editing and Publishing Content to the Web
4. Netlify + Dropbox: Saving a Text File as a Command for Publishing and Deploying Your Site

**Comment by verythorough** [comment]
@jimniels Yep, that covers the steps nicely. The one correction is that there's no underscore in `netlify.toml`.  (Though, of course, there _is_ an underscore in the alternative place to describe redirects, `_redirects`!)

**Comment by jimniels** [comment]
@verythorough two questions:

### First 

I'm trying the approach you recommended. I was able to get the verification request to work via my netlify function. However, the redirect that now proxies the Dropbox webhook seems to not be giving me results that are as consistent as they were when the function was forwarding them on. I'm not sure why that is? 

By that, what I mean is, I'll save a file in Dropbox and sometimes it'll trigger a deploy in Netlify and sometimes it won't. I can't seem to find a consistent pattern as to when it decides it will build and when it decides it doesn't want to. 

Previously, when the function was forwarding the Webhooks, I found predictable results. I could save a file every minute with new content and it would trigger a build for each file save. But with this new method, if I save a file every minute with new content, it never triggers a build with any consistency. Sometimes it'll trigger two close together, sometimes I'll go 5, even 10 minutes across multiple file saves before another build will trigger.

Is there like a timeout window that Netlify has set behind the scenes for build hook triggers? 

My results with this method were wildly inconsistent. I'm wondering if there's a way I might go about fixing that?

In fact, at the time of me posting this comment (8:30PM), it's been >30 minutes since the last time a build was triggered by a Dropbox file save. And I haven't changed any code since the first one triggered at 7:28PM (see screenshot). So I'm not sure what's going on?

screen shot 2018-10-03 at 8 30 34 pm

You can see 6 builds were triggered by the webhook there over the course of about an hour. There were probably ... just guessing here ... at least 20 file saves over that course of time. some worked, most didn't. I have no idea why. It was much more consistent when all webhooks were going to my functions endpoint.

### Second

Can I inject an environment variable in my `netlify.toml` file? 

At first I though [maybe I'd be able to use](https://www.netlify.com/docs/continuous-deployment/#build-environment-variables) the the `WEBHOOK_URL`

> If your build is triggered from one of your inbound webhooks, Netlify also has three webhook-specific variables...WEBHOOK_URL

So using it like:

```
# netlify.toml
[[redirects]]
  from = "/dropbox-webhook"
  to = "WEBHOOK_URL"
  status = 200
```

But that didn't work. Then I tried saving the build hook URL as an environment variable via the Netlify UI and then injecting like an example I saw in the docs:

screen shot 2018-10-03 at 8 07 28 pm

So like this:

```
# netlify.toml
[[redirects]]
  from = "/dropbox-webhook"
  to = "NETLIFY_BUILD_HOOK_URL"
  status = 200
```

But that didn't work either. In the end, the only way I could get it to work, was to hard-code the URL I generate in Netlify directly into my `netlify.toml` file, i.e.

```
# netlify.toml
[[redirects]]
  from = "/dropbox-webhook"
  to = "https://api.netlify.com/build_hooks/abc123"
  status = 200
```

That's the only way I could get the Dropbox webhook working. Am I doing something wrong? It's possible that the inconsistent results I was getting (as described in the "first" problem) mean one of the prior methods was, in fact, working, but I just never saw a build triggered.

**Comment by jimniels** [comment]
FWIW: I added my function endpoint back as a webhook in Dropbox, just to make sure webhooks from dropbox were working.

screen shot 2018-10-03 at 8 56 02 pm

In theory, I should get a webhook at both my function endpoint and my proxy redirect URL (which should trigger a build).

No builds were getting triggered at all. The proxy redirect URI doesn't seem to be working.

But my function endpoint was receiving it's webhooks (but wasn't trigger a build because I took out the code that was forwarding on the request).

screen shot 2018-10-03 at 8 57 00 pm

I have no idea why this is. FWIW my current redirect in my `netlify.toml` file looks like this:

```
[[redirects]]
  from = "/dropbox-webhook"
  to = "https://api.netlify.com/build_hooks/MY_UNIQUE_ID"
  status = 200
```

**Comment by jimniels** [comment]
Ah noticed this piece of info from Dropbox this morning:

screen shot 2018-10-04 at 11 19 03 am

**Comment by sw-yx** [comment]
btw jim i tried out the same flow and got the same issue as you. trying to figure it out now, i dont know the answer as i'm still new around here.

**Comment by swyxio** [comment]
Edit: redacted because i got it working but basically did not resolve Jim's issue below

**Comment by jimniels** [comment]
@sw-yx wait, from what I can tell, the steps you followed are the same ones I followed last night. I got it working too, but my problem is that it was incredibly inconsistent. I edited and saved different files  probably at least 20 times over a period of 30 minutes, so you would think 20 builds were triggered, but nope, only like 4 were triggered. 

Sometimes I'll save a file and it will trigger a build, but most of the time I'll save a file and it won't. I don't know why it's so inconsistent. It wasn't this way when I was only using the function endpoint.

Is yours working consistently? Like if edit and save a file 5 times over 5 minutes, does it trigger 5 builds?

**Comment by swyxio** [comment]
Hey Jim, i couldnt replicate that but i may not have the same dropbox setup as you. interestingly i found that the dropbox build hook  doesnt trigger when i delete files, only when i add files. there maybe some debouncing going on when you edit and save files that quickly. but that also doesnt explain the inconsistent behavior you saw between functions and hooks.

there aren't any limits on redirects that we are aware of, and when i think closely about it its probably more likely due to how dropbox does its hooks than due to some weird behavior with our redirects (since redirecting is by far the simpler process).

I dont think this is a publishing blocker, and would like to move ahead with publishing the post if everyone is happy with this setup.

re: title - i like your first: "Combining Netlify with Dropbox For a One-Click Publishing Process".

**Comment by jimniels** [comment]
TBH, I don't feel good publishing with this new method, as it's been a really inconsistent experience for me thus far.

I re-setup everything again today doing exactly what you did and I've added content, deleted content, and edited existing content, all multiple times in Dropbox over the past 2 or 3 hours and I've only been able to trigger the build hook from Dropbox once. *Only once.* Is your setup working consistently? At this point, I'd rather switch back to the functions method of doing it, as it worked perfectly, every single time I added, removed, or edited content.

---

re: title, that works for me 👍

**Comment by jimniels** [comment]
@sw-yx hey sorry, I was on vacation Thursday last week until today, so I'm just getting a chance to come back to this (with fresh eyes, which is probably a good thing)

So I tried a few test this morning. I figured I'd try creating a file in Dropbox and saving it once every minute. I'd do this for two different scenarios: 

1. Dropbox sends a webhook to my netlify function, which forwards it to a build hook URI I generate specifically for that Netlify function
2. Dropbox sends a webhook to my proxy redirect, which forwards it to a build hook URI I Generate specifically for that proxy redirect

Then I enabled/disabled each one and tried the test.

screen shot 2018-10-09 at 9 46 09 am

First, I enabled the webhook in Dropbox which points at the proxy redirect. The expectation was that every minute I saved a file, a new build should show up in Netlify. Nothing happened.

Second, I disabled the first webhook in Dropbox then enabled the other one which points at the netlify function redirect. The expectation was that every minute I saved a file, a new build would show up. And it worked flawlessly.

screen shot 2018-10-09 at 9 51 33 am

This was as I expected. Dropbox webhooks via the proxy redirect method don't seem to work at all, or they don't work consistently (at least for me). Dropbox webhooks via the Netlify function method work flawlessly every time.

For this reason, I would still prefer the post be published in its original form using the "netlify functions method" for Dropbox webhooks (unless someone at Netlify wants to dig into what's going on here and possibly fix this?)

**Comment by jimniels** [comment]
Sidenote: I'm having a hard time troubleshooting all of this because my Netlify function invocations are inconsistent. Look at this log:

screen shot 2018-10-09 at 11 09 57 am

That first invocation at 10:57 was when I pushed some code changing how the function works. But all the subsequent invocations are using code from before the 10:57 invocation (note how the log messages differ? that code changes that happened at 10:57 are no longer happening when the function is invoked; rather, it seems to be leverage some old — presumably cached — version of the function?).

Suffice it to say I'm having a hard time troubleshooting this. The only thing I can get to work with any consistency is the original approach to this blog post.

**Comment by swyxio** [comment]
Hey Jim, sorry this is happening. It's very frustrating. I have copied this to support to see what is going on with the function invocation. Hopefully we'll get an answer there. 

I'm still keen to publish your post. Trying to see what we should do now.

**Comment by jimniels** [comment]
@sw-yx 

Personally, I like the approach of setting up the proxy redirect and only having to invoke the function once. And I'm happy to write the blog post and repo README to accommodate that revised approach. However, I personally have not been able to get that approach to work with any kind of consistency. On the other hand, the approach of using a custom function has worked consistently every time I've tried it. 

So at this point, my feelings are: I can refine the post the original way I had it (using the functions approach) and we can publish it. Or, you could hook me up with some support folks over there and we can dive further into why the proxy redirect isn't working as expected. Then, once we fix it and get it working consistently, I'll be happy to revise my original post so it suits this new approach and we can publish that way.

Let me know how you'd like to proceed.

**Comment by swyxio** [comment]
Hey Jim! yeah I think we should proceed with the functions approach for now. I will go ahead and schedule it to be published for tomorrow. 

In the meantime I've talked to support (Chris aka "fool") about this and they want it submitted through proper channels. Do you mind dropping a link to this issue into https://www.netlify.com/support/? They've already seen this issue once but need it to follow up with platform folks. I am also quite uncomfortable with how we can't explain the unreliability of this and would love an explanation/fix.

**Comment by jimniels** [comment]
@sw-yx woah, wasn't expecting a tomorrow publish date ha, but that sounds good. Let me update the post draft a bit with the title and all and I'll post when it's ready.

I'll also post an issue in support when I get the chance. Thanks!

**Comment by jimniels** [comment]
Ok @sw-yx I had to roll back some changes I'd made to the blog post and master branches, since we're sticking with the original way of doing things.

With that said, I proof-read everything and what you see in this branch in terms of the blog post should be good to go (I'm not sure how you'll host the image, but feel free to link to that however you want).

If there's any chance you could let me know the URL of the blog post before (or shortly after) it goes live, let me know so I can update the README in the `master` branch with it.

Also, if you could just read through the blog post once more and try setting it up yourself (or have someone there at Netlify follow my instructions for setting it up) just to give it all one more sanity check before going live, that'd be awesome :)

Thank you very much!

**Comment by swyxio** [comment]
thanks Jim! no worries as we can update things after we publish stuff :)

Yes I've gone through it and everything looks good. Will update this comment with the published URL.

Edit: Hey @jimniels!! thank you for the post! it is up at https://www.netlify.com/blog/2018/10/15/combining-netlify-with-dropbox-for-a-one-click-publishing-process/ and we will promote it soon. Loved this process and it should be really handy for fellow Dropbox + Netlify users too!

**Comment by jimniels** [comment]
@sw-yx  🎉  woot woot!

Updated the readme with the link. I think we're all good here, gonna go ahead and close this. Thanks for all the feedback. Pleasure working with you sir :)

**Pull request closed without merging**
